export type CLEAR_GREETING = "CLEAR_GREETING";
export type UPDATE_GREETING = "UPDATE_GREETING";
export type CHANGE_LANGUAGE = "CHANGE_LANGUAGE";
export type INCREASE_COUNTER = "INCREASE_COUNTER";
export type INCREASE_COUNTER_ASYNC = "INCREASE_COUNTER_ASYNC";
export type INCREASING_COUNTER = "INCREASING_COUNTER";
